### ISSUE TITLE
最新版本下载

### ISSUE THREAD

**Issue by LLLLLea** [xiaoshuaishuai319/weixinxiaochengxu#1]
您好，我对您开发的这款微信小程序非常感兴趣，但在github和码云的链接里，都没有找到您的最新版本的程序，就是包含人脸识别和相似度的小程序代码，请问您可以分享下最新版的微信小程序吗

**Comment by xiaoshuaishuai319** [comment]
https://gitee.com/xshuai/weixinxiaochengxu/tree/master/pages/facedetectcrossageface 这个码云是最新的。只是有小程序代码。后端代码暂时还没完善好。可以看代码片段。鄙人后端使用Java语言  https://gitee.com/xshuai/codes/7vq4n38grhkb6p1c9ix2t32

"pages/facedetectcrossageface/facedetectcrossageface" 
是这个页面 确实是页面少提交了一个代码 https://gitee.com/xshuai/weixinxiaochengxu/blob/master/pages/nine/nine.js 
你可以自己改下里面的代码。页面路径引用一下即可
